version: '3'
services:
  # NodeJS Backend
  backend:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - dse
    env_file: ./killrvideo.env
    environment:
      NODE_ENV: development

  # Datastax Enterprise 
  dse:
    image: datastax/dse-server:6.7.0
    command: [ -s -g ]
    ports:
      - "9042:9042"
      - "8983:8983"
      - "8182:8182"
    env_file: ./killrvideo.env
    environment:
      DS_LICENSE: accept
    # Allow DSE to lock memory with mlock
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1

  # Frontend
  web:
    image: killrvideo/killrvideo-web:3.0.1
    env_file: ./killrvideo.env
    ports:
      - "3000:3000"
    depends_on:
      - dse

  # DSE Configurator to setup DSE
  dse-config:
    image: killrvideo/killrvideo-dse-config:3.0.0
    env_file: ./killrvideo.env
    depends_on:
      - dse

  # Sample Data Generator
  generator:
    image: killrvideo/killrvideo-generator:3.0.2
    env_file: ./killrvideo.env
    depends_on:
      - dse
      - backend

  # DataStax Studio
  studio:
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091"
    depends_on:
      - dse
    environment:
      DS_LICENSE: accept
